### ISSUE TITLE
Sync Docker module with ci.docker

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/open-liberty-masterclass#8]
Update the section on Docker to be in sync/consistent with what we suggest per https://github.com/OpenLiberty/ci.docker/

Do the same for Dockerfiles used too.

**Comment by yeekangc** [comment]
In particular, we want to sync up on the use of `configure.sh`.

Overall flow should be use official OL image, drop the war, and that's it.

**Comment by jamiecoleman92** [comment]
Done!
